// export-script — turn any probe result into a self-contained runnable .py.
//
// The tool that teaches you to leave the tool: every result card can export
// the experiment it just ran as a standalone script (pip install + load +
// probe + print), reproducible outside the workbench. Honesty rule: kinds
// whose script is genuinely runnable get real code; bespoke kinds (J-lens
// runs on the workbench's vendored engine) export a clearly-marked sketch.

import type { ProbeRun } from './ProbeResultCard.js';

const PREAMBLE = (modelId: string) => `# Generated by Anatomist — a reproducible probe script.
#
#   pip install transformer_lens torch
#
# Runs standalone: loads the model, runs the probe, prints the result.

import torch
from transformer_lens import HookedTransformer

model = HookedTransformer.from_pretrained(${py(modelId)})
`;

function py(s: string): string {
  return JSON.stringify(s);
}

type Params = ProbeRun['params'];

const BUILDERS: Record<string, (p: Params, modelId: string) => string | null> = {
  'attention-heatmap': (p, m) => `${PREAMBLE(m)}
prompt = ${py(p.prompt)}
_, cache = model.run_with_cache(prompt)
pattern = cache["blocks.${p.layer}.attn.hook_pattern"][0, ${p.head}]  # [T, T]
tokens = model.to_str_tokens(prompt)

print(f"attention pattern, layer ${p.layer} head ${p.head}")
for i, row in enumerate(pattern):
    top = int(row.argmax())
    print(f"  {tokens[i]!r:>14} looks most at {tokens[top]!r} ({float(row[top]):.2f})")
`,

  'logit-list': (p, m) => `${PREAMBLE(m)}
prompt = ${py(p.prompt)}
_, cache = model.run_with_cache(prompt)
resid = cache["blocks.${p.layer}.hook_resid_post"][0, -1]
# The lesson this workbench earned: apply the FINAL LayerNorm before W_U,
# or the mid-layer readout comes out miscalibrated.
scaled = model.ln_final(resid.unsqueeze(0).unsqueeze(0))[0, 0]
logits = scaled @ model.W_U + model.b_U
probs = logits.softmax(-1)
top = logits.topk(${p.top_k})
print(f"logit lens at layer ${p.layer} (final token):")
for v, i in zip(top.values, top.indices):
    print(f"  {model.to_string([int(i)])!r:>14}  p={float(probs[i]):.3f}")
`,

  'ablation-compare': (p, m) => `${PREAMBLE(m)}
prompt = ${py(p.prompt)}
tokens = model.to_tokens(prompt)

clean = model(tokens)[0, -1]

def zero_head(z, hook):
    z[:, :, ${p.head}, :] = 0.0
    return z

ablated = model.run_with_hooks(
    tokens, fwd_hooks=[("blocks.${p.layer}.attn.hook_z", zero_head)]
)[0, -1]

for name, logits in [("clean", clean), ("L${p.layer}H${p.head} ablated", ablated)]:
    top = logits.topk(5)
    print(name, [(model.to_string([int(i)]), round(float(v), 2)) for v, i in zip(top.values, top.indices)])
`,

  'token-heat-surprisal': (p, m) => `${PREAMBLE(m)}
import math

prompt = ${py(p.prompt)}
tokens = model.to_tokens(prompt)
logits = model(tokens)[0].float()
logprobs = logits.log_softmax(-1)
strs = model.to_str_tokens(prompt)

print("surprisal (bits) per token — the loss, made visible:")
for t in range(1, len(strs)):
    bits = -float(logprobs[t - 1, tokens[0, t]]) / math.log(2)
    bar = "#" * int(min(bits, 20))
    print(f"  {strs[t]!r:>14} {bits:6.2f} {bar}")
`,

  'token-heat-unit': (p, m) => `${PREAMBLE(m)}
prompt = ${py(p.prompt)}
_, cache = model.run_with_cache(prompt)
acts = cache["blocks.${p.layer}.mlp.hook_post"][0][:, ${p.head}]
for tok, a in zip(model.to_str_tokens(prompt), acts):
    print(f"  {tok!r:>14} {float(a):+8.3f}")
`,

  'generation-trace': (p, m) => `${PREAMBLE(m)}
prompt = ${py(p.prompt)}
tokens = model.to_tokens(prompt)
temperature = 0.8

for _ in range(16):
    logits = model(tokens)[0, -1].float()
    probs = logits.softmax(-1)
    entropy = float(-(probs * (probs + 1e-12).log2()).sum())
    next_id = int(torch.multinomial((logits / temperature).softmax(-1), 1))
    print(f"chose {model.to_string([next_id])!r:>12}  p={float(probs[next_id]):.2f}  H={entropy:5.2f} bits")
    tokens = torch.cat([tokens, torch.tensor([[next_id]])], dim=1)
`,

  tokenizer: (p, m) => `${PREAMBLE(m)}
prompt = ${py(p.prompt)}
ids = model.to_tokens(prompt, prepend_bos=False)[0]
print([model.to_string([int(i)]) for i in ids])
# the footgun: these are DIFFERENT tokens
print(model.to_tokens("poised", prepend_bos=False)[0].tolist())
print(model.to_tokens(" poised", prepend_bos=False)[0].tolist())
`,

  'head-census': (_p, m) => `${PREAMBLE(m)}
# Census every head on a random repeated sequence — the induction test.
P = 50
g = torch.Generator().manual_seed(42)
half = torch.randint(1000, model.cfg.d_vocab - 1000, (1, P), generator=g)
seq = torch.cat([torch.tensor([[model.tokenizer.bos_token_id or 50256]]), half, half], dim=1)
_, cache = model.run_with_cache(seq)
T = seq.shape[1]

best = {"prev": (0, None), "induction": (0, None)}
for L in range(model.cfg.n_layers):
    pat = cache[f"blocks.{L}.attn.hook_pattern"][0]
    for h in range(model.cfg.n_heads):
        prev = float(torch.stack([pat[h, i, i - 1] for i in range(1, T)]).mean())
        ind = float(torch.stack([pat[h, i, i - P + 1] for i in range(P + 1, T)]).mean())
        if prev > best["prev"][0]: best["prev"] = (prev, f"L{L}H{h}")
        if ind > best["induction"][0]: best["induction"] = (ind, f"L{L}H{h}")
print(best)  # gpt2-small: prev -> L4H11, induction -> L5H5 (the literature's heads)
`,

  'token-heat-saliency': (p, m) => `${PREAMBLE(m)}
prompt = ${py(p.prompt)}
target = ${py(p.answer ?? ' the')}
tokens = model.to_tokens(prompt)
target_id = model.to_tokens(target, prepend_bos=False)[0, 0]

cap = {}
def grab(value, hook):
    value.retain_grad(); cap["e"] = value; return value

logits = model.run_with_hooks(tokens, fwd_hooks=[("hook_embed", grab)])[0, -1]
logits[int(target_id)].backward()
# gradient NORM, not grad x input — grad x input failed faithfulness under
# LayerNorm when we tested it (it buried the Eiffel tokens).
sal = cap["e"].grad[0].norm(dim=-1)
for tok, v in zip(model.to_str_tokens(prompt), sal):
    print(f"  {tok!r:>14} {float(v):6.3f}")
`,

  'weight-lens': (p, m) => `${PREAMBLE(m)}
# Read one neuron's wiring — zero forward passes.
w_in = model.W_in[${p.layer}, :, ${p.head}].float()
w_out = model.W_out[${p.layer}, ${p.head}].float()
W_E, W_U = model.W_E.float(), model.W_U.float()

cos = (W_E / W_E.norm(dim=-1, keepdim=True)) @ (w_in / w_in.norm())
print("reads:    ", [model.to_string([int(i)]) for i in cos.topk(${p.top_k}).indices])
out = w_out @ W_U
print("promotes: ", [model.to_string([int(i)]) for i in out.topk(${p.top_k}).indices])
print("suppresses:", [model.to_string([int(i)]) for i in (-out).topk(${p.top_k}).indices])
`,

  'sae-feature-list': (p, _m) => `# Generated by Anatomist — SAE feature readout.
#
#   pip install sae-lens
# (Own environment recommended: sae_lens pins its own TransformerLens/torch.)

import torch
from sae_lens import SAE, HookedSAETransformer

model = HookedSAETransformer.from_pretrained("gpt2")
sae = SAE.from_pretrained(release="gpt2-small-res-jb", sae_id="blocks.${p.layer}.hook_resid_pre")
sae = sae[0] if isinstance(sae, tuple) else sae

prompt = ${py(p.prompt)}
_, cache = model.run_with_cache(model.to_tokens(prompt))
x = cache[sae.cfg.metadata.hook_name if hasattr(sae.cfg, "metadata") else sae.cfg.hook_name][0]
feats = sae.encode(x.to(sae.W_dec.device))

topv, topi = feats[-1].topk(${p.top_k})
for v, fi in zip(topv, topi):
    labels = [model.to_string([int(t)]) for t in (sae.W_dec[int(fi)] @ model.W_U).topk(6).indices]
    print(f"f{int(fi):>6} act={float(v):5.1f}  promotes: {labels}")
`,
};

/** Build a runnable (or clearly-marked sketch) script for a probe run. */
export function buildScript(run: ProbeRun, modelId: string): { filename: string; code: string } {
  const builder = BUILDERS[run.result.kind];
  const filename = `${run.probe.id.replace(/-/g, '_')}_probe.py`;
  if (builder) {
    const code = builder(run.params, modelId);
    if (code) return { filename, code };
  }
  // Honest fallback: the pedagogical sketch, labeled as such.
  return {
    filename,
    code: `# Generated by Anatomist.
#
# NOTE: this probe (${run.probe.shortLabel}) runs on workbench-specific
# machinery, so this export is the CONCEPTUAL CORE as pseudocode — the shapes
# and math are exact, but helper functions are sketched, not defined.
# The workbench source (apps/mi-backend) has the full implementation.

${run.probe.codeTemplate
  .replace(/\{layer\}/g, String(run.params.layer))
  .replace(/\{head\}/g, String(run.params.head))
  .replace(/\{top_k\}/g, String(run.params.top_k))}
`,
  };
}

/** Trigger a browser download of the script. */
export function downloadScript(run: ProbeRun, modelId: string): void {
  const { filename, code } = buildScript(run, modelId);
  const blob = new Blob([code], { type: 'text/x-python' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
